Repository nuttyartist/notes, pull requests merged in 2023-02, with the labels that each got.

#451 Toggle window visibility upon system tray activation
  src/mainwindow.cpp
  src/mainwindow.h
Labels: Enhancement/Polish, UX

#426 initial try to improve tagging experience, #354
  src/notelistview.cpp
  src/notelistview.h
Labels: Enhancement/Polish, UX

#479 Tab width is way too high, fixed by setting it to the width of 4 spaces.
  src/mainwindow.cpp
Labels: UI

#487 Fix settings not saving when closing the app using native buttons or system shortcut
  src/mainwindow.cpp
Labels: Bug

#503 Fixes panel widths resetting when resizing (fixes #482)
  src/mainwindow.cpp
  src/mainwindow.h
Labels: Bug, UI
